// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CpuInfo() {
  return window['go']['main']['App']['CpuInfo']();
}

export function DiskInfo() {
  return window['go']['main']['App']['DiskInfo']();
}

export function GetCPUUsage() {
  return window['go']['main']['App']['GetCPUUsage']();
}

export function GetMemUsage() {
  return window['go']['main']['App']['GetMemUsage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HostInfo() {
  return window['go']['main']['App']['HostInfo']();
}

export function MemInfo() {
  return window['go']['main']['App']['MemInfo']();
}
