// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sys} from '../models';

export function CpuInfo():Promise<string>;

export function DiskInfo():Promise<string>;

export function GetCPUUsage():Promise<main.CPUUsage>;

export function GetMemUsage():Promise<sys.MemoryInfo>;

export function Greet(arg1:string):Promise<string>;

export function HostInfo():Promise<string>;

export function MemInfo():Promise<string>;
